# Site settings
title: Kyle Hogan
email: klhogan@bu.edu
description: > # this means to ignore newlines until "baseurl:"
  Hopefully this works. Please?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kylehogan.github.io" # the base hostname & protocol for your site
github_username:  kylehogan

# Build settings
markdown: kramdown
